#
# Derived from
# https://github.com/steveno/ctags/blob/master/.travis.yml
#

dist: xenial

language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

sudo: true

addons:
  apt:
    packages:
      - lcov
      - procps
      - netcat
before_install:
  - |
    gem install lcoveralls

script:
  - |
    case $TRAVIS_OS_NAME in
        linux) dialect=linux;;
        osx)   dialect=darwin;;
    esac
    ./Configure -n $dialect

  - |
    if [ $CC = 'gcc' ]; then
        CC_EXTRA="--coverage"
    fi
    make CDEF="${CC_EXTRA}" CC="${CC} ${CC_EXTRA}"

  - |
    case $TRAVIS_OS_NAME in
        linux) dialect=linux;;
        osx)   dialect=darwin;;
    esac
    tdir=dialects/${dialect}/tests
    if [ -f ${tdir}/Makefile ]; then
        make -C "${tdir}"
    fi

  - |
    case $TRAVIS_OS_NAME in
        linux) dialect=linux;;
        osx)   dialect=darwin;;
    esac
    sudo -E bash ./check.bash $dialect

after_success:
  - |
    if [ $CC = 'gcc' ] && [ $TRAVIS_OS_NAME = 'linux' ]; then
    (
            for f in /home/travis/.rvm/gems/ruby-2*/gems/lcoveralls-*/lib/lcoveralls/color_formatter.rb; do
                    sed -i -e 's/severity.capitalize!/severity = severity.capitalize/' $f
            done
            for f in /home/travis/.rvm/gems/ruby-2*/gems/lcoveralls-*/lib/lcoveralls/runner.rb; do
                    sed -i -e 's/\(.*format.*f\)\(%\)\('"'"'.*$\)/\1%%\3/' $f
            done
    ) || :
    lcov -c -b . -d . -o coverage.info && lcoveralls --root . --retry-count 5 coverage.info
    fi
